In [83]:
#importing numpy library as np
import numpy as np

In [84]:
#using array function to create arrays
a=np.array([[1,2],[6,7]])
b=np.array([[11,12],[16,17]])

In [85]:
print(a[1:2,0:2])#printing array

[[6 7]]


In [86]:
print(a)
print(b)
mul=np.dot(a,b)#matrix multiplication
print(mul)

[[1 2]
 [6 7]]
[[11 12]
 [16 17]]
[[ 43  46]
 [178 191]]


In [87]:
mul1=np.multiply(a,b) #normal multiplication
print(mul1)

[[ 11  24]
 [ 96 119]]


In [88]:
add1=np.add(a,b)#addition
print(add1)

[[12 14]
 [22 24]]


In [89]:
print(a)
print(b)
sub=np.subtract(a,b)#sybtraction
print(sub)

[[1 2]
 [6 7]]
[[11 12]
 [16 17]]
[[-10 -10]
 [-10 -10]]


In [90]:
dev=np.divide(a,b)#division
print(dev)

[[0.09090909 0.16666667]
 [0.375      0.41176471]]


In [91]:
n1=np.array([[10,20,30],[40,50,60]])
n2=np.array([[15,25,35],[45,55,65]])
div1=np.divide(n1,n2)#array matrix division
print(div1)

[[0.66666667 0.8        0.85714286]
 [0.88888889 0.90909091 0.92307692]]


In [92]:
print("shape a:{}".format(a.shape)) #shape: To get the dimensions of the array.
print("ndim {}".format(a.ndim))#ndim: To find out how many dimensions the array has.
print("size {}".format(a.size))#size: To determine the total number of elements in the array.
print(f"dtype {a.dtype}")#dtype: To check the data type of the elements in the array.
print(f"itemsize {a.itemsize}")#itemsize: To find out how much memory each element takes.
print(f"data {a.data}")#data: To access the raw data buffer of the array.

shape a:(2, 2)
ndim 2
size 4
dtype int64
itemsize 8
data <memory at 0x7fb210b64ee0>


In [93]:
a1 = np.array([[2, 3, 4, 5],
               [1, 4, 7, 6]])
a2 = np.array([[1, 1, 1], [1, 1, 1]])

# Slicing the array
sliced_arr = a1[:2, :2]
print("Sliced Array:")
print(sliced_arr)


Sliced Array:
[[2 3]
 [1 4]]


In [94]:
# Using advanced indexing to extract elements from 'a1' at positions (1, 2) and (1, 1).
index_arr=a1[[1,1],[2,1]]
print(index_arr)

[7 4]


In [95]:
# Calculating the sum of all elements in 'a1'
arr=np.array([[25,64],[89,36]])
print(arr.sum())

214


In [96]:
#indicate that not all elements in the array are True, 
#and only the second column contains all True values.

bool=np.array([[True,True],[False,True]])
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))

all() with axis none False
all() with axis 0 [False  True]


In [97]:
n3=np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])
#arange(): Generates a sequence of numbers.
re=n3.reshape(4,4)#reshape3 'n3' into 4x4 array
print(re)#print thereshaped array
n3=np.arange(9)
print(n3)
#reshape(): Reshapes the array into a specified shape.


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
[0 1 2 3 4 5 6 7 8]


In [98]:
#it extracts the first and second columns from the array
print(np.take(re,[0,1],axis=1))

[[ 10  20]
 [ 50  60]
 [ 90 100]
 [130 140]]


In [99]:
print(n3.min())#minimum value of n3
print(n3.max())#maximum value of n3
print(re.max(axis=1))#print max along each row
print(re.min(axis=0))#print min along each row

0
8
[ 40  80 120 160]
[10 20 30 40]


In [100]:
print(n1)
print(np.sqrt(n1))#print the square root of n1
print(np.std(n1))#print the standard deviation of n1

[[10 20 30]
 [40 50 60]]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
17.07825127659933


In [101]:
v=np.vstack((n1,n2))#stacking arrays vertically
print(v)
h=np.hstack((n1,n2))#stacking arrays horizontally
print(h)

[[10 20 30]
 [40 50 60]
 [15 25 35]
 [45 55 65]]
[[10 20 30 15 25 35]
 [40 50 60 45 55 65]]


In [102]:
arr=np.arange(0,20,3)#create an array with elements from 0 to 20 with a step of 3
print(arr)

[ 0  3  6  9 12 15 18]


In [103]:
arr=np.arange(0,50,3,float)#create an array with elements from 0 to 50 with a step of 3 and data type float
print(arr)
print(arr.dtype)

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48.]
float64


In [104]:
arr=np.linspace(0,50,3)#create an array with elements from 0 to 50 with 3 elements
print(arr)
print(arr.dtype)

[ 0. 25. 50.]
float64


In [105]:
#transpose the array
hr=h.T
print(hr)

[[10 40]
 [20 50]
 [30 60]
 [15 45]
 [25 55]
 [35 65]]


In [106]:
#iterating through the array
for i in np.nditer(hr):
    print("AK",i)

AK 10
AK 20
AK 30
AK 15
AK 25
AK 35
AK 40
AK 50
AK 60
AK 45
AK 55
AK 65


In [107]:
#hsplit(): Splits an array horizontally (along columns).
h_split=np.hsplit(h,3)
print("hsplit:",h_split)

#vsplit(): Splits an array vertically (along rows).
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

hsplit: [array([[10, 20],
       [40, 50]]), array([[30, 15],
       [60, 45]]), array([[25, 35],
       [55, 65]])]
vsplit: [array([[10, 20, 30, 15, 25, 35]]), array([[40, 50, 60, 45, 55, 65]])]


In [108]:
from scipy import stats as st 
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("mode:",st.mode(arr))

mean: 25.0
median: 25.0
mode: ModeResult(mode=array([0.]), count=array([1]))
