<a href="https://colab.research.google.com/github/Heytthere/PythonProjects/blob/main/PracticeSVC%26DT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt

In [66]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)


In [67]:
print(df[['sepal length (cm)', 'species']].head())

   sepal length (cm) species
0                5.1  setosa
1                4.9  setosa
2                4.7  setosa
3                4.6  setosa
4                5.0  setosa


In [68]:
print(df[df['petal width (cm)'] > 1.5])

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
56                 6.3               3.3                4.7               1.6   
70                 5.9               3.2                4.8               1.8   
77                 6.7               3.0                5.0               1.7   
83                 6.0               2.7                5.1               1.6   
85                 6.0               3.4                4.5               1.6   
100                6.3               3.3                6.0               2.5   
101                5.8               2.7                5.1               1.9   
102                7.1               3.0                5.9               2.1   
103                6.3               2.9                5.6               1.8   
104                6.5               3.0                5.8               2.2   
105                7.6               3.0                6.6               2.1   
106                4.9      

In [69]:
print("Sum of petal lengths:", df['petal length (cm)'].sum())

Sum of petal lengths: 563.7


In [70]:
df['sepal_area'] = df['sepal length (cm)'] * df['sepal width (cm)']
print(df[['sepal_area']].head())

   sepal_area
0       17.85
1       14.70
2       15.04
3       14.26
4       18.00


In [71]:
print("Max petal length for Setosa:", df[df['species'] == 'setosa']['petal length (cm)'].max())

Max petal length for Setosa: 1.9


In [72]:
print(df.groupby('species')['sepal length (cm)'].max())

species
setosa        5.8
versicolor    7.0
virginica     7.9
Name: sepal length (cm), dtype: float64


<ipython-input-72-771716d4880d>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('species')['sepal length (cm)'].max())


In [73]:
X = df.drop('species', axis=1)
y = df['species']

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print shape of each set
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (120, 5)
X_test shape: (30, 5)
y_train shape: (120,)
y_test shape: (30,)


In [76]:
svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_preds = svm_model.predict(X_test)

In [77]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_preds = dt_model.predict(X_test)

In [78]:
# SVM Metrics
svm_cm = confusion_matrix(y_test, svm_preds)
svm_acc = accuracy_score(y_test, svm_preds)

# Decision Tree Metrics
dt_cm = confusion_matrix(y_test, dt_preds)
dt_acc = accuracy_score(y_test, dt_preds)

print("SVM Confusion Matrix:\n", svm_cm)
print("SVM Accuracy:", round(svm_acc, 2))

print("\nDecision Tree Confusion Matrix:\n", dt_cm)
print("Decision Tree Accuracy:", round(dt_acc, 2))


SVM Confusion Matrix:
 [[10  0  0]
 [ 0  7  2]
 [ 0  1 10]]
SVM Accuracy: 0.9

Decision Tree Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Decision Tree Accuracy: 1.0
